# Generated by Django 5.2.16 on 2026-07-20 22:57

import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(max_length=160)),
                ('office_type', models.CharField(choices=[('carrier', 'Carrier'), ('branch', 'Branch'), ('authorized_agent', 'Authorized agent'), ('garage_office', 'Garage office')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('conditional', 'Conditional'), ('active', 'Active'), ('restricted', 'Restricted'), ('no_new_bookings', 'No new bookings'), ('wind_down', 'Wind down'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('timezone', models.CharField(default='Asia/Damascus', max_length=64)),
                ('default_currency', models.CharField(default='SYP', max_length=3)),
                ('support_phone', models.CharField(max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('commission_profile_id', models.UUIDField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offices',
            },
        ),
        migrations.CreateModel(
            name='TransportOperator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, max_length=160, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='draft', max_length=24)),
                ('country_code', models.CharField(default='SY', max_length=2)),
                ('support_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_operators',
            },
        ),
        migrations.CreateModel(
            name='OfficeBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('location_id', models.UUIDField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='branches', to='organizations.office')),
            ],
            options={
                'db_table': 'office_branches',
            },
        ),
        migrations.CreateModel(
            name='OfficeMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('can_approve_own_actions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to='organizations.officebranch')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to='organizations.office')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to='identity.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='office_memberships', to='identity.user')),
            ],
            options={
                'db_table': 'office_memberships',
            },
        ),
        migrations.AddField(
            model_name='office',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='offices', to='organizations.transportoperator'),
        ),
        migrations.AddConstraint(
            model_name='officebranch',
            constraint=models.UniqueConstraint(fields=('office', 'name'), name='uq_office_branch_name'),
        ),
        migrations.AddConstraint(
            model_name='officebranch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('office',), name='uq_primary_branch'),
        ),
        migrations.AddConstraint(
            model_name='officemembership',
            constraint=models.UniqueConstraint(fields=('user', 'office', 'branch', 'role'), name='uq_membership_nullsafe', nulls_distinct=False),
        ),
    ]
