# Generated by Django 5.2.16 on 2026-07-20 23:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officebranch',
            name='location_id',
        ),
        migrations.AddField(
            model_name='officebranch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='office_branches', to='geography.location'),
        ),
        migrations.AddField(
            model_name='officebranch',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='VerificationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='verification_cases', to='organizations.office')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('info_required', 'Information required'), ('external_verification', 'External verification'), ('conditional', 'Conditional'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=24)),
                ('risk_level', models.CharField(choices=[('basic', 'Basic'), ('documented', 'Documented'), ('enhanced', 'Enhanced')], default='basic', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='verification_reviews', to='identity.user')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='verification_approvals', to='identity.user')),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('conditions', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'verification_cases',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['status', 'risk_level'], name='ix_verification_status_risk'), models.Index(fields=['office', '-version'], name='ix_verification_office_version')],
                'constraints': [models.UniqueConstraint(fields=('office', 'version'), name='uq_verification_case_version')],
            },
        ),
        migrations.CreateModel(
            name='OfficeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='organizations.office')),
                ('verification_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='organizations.verificationcase')),
                ('document_type', models.CharField(max_length=64)),
                ('storage_object_key', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reviewed_office_documents', to='identity.user')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'office_documents',
                'indexes': [models.Index(fields=['office', 'status', 'expires_at'], name='ix_office_doc_validity')],
                'constraints': [models.UniqueConstraint(fields=('office', 'document_type', 'sha256'), name='uq_office_document_hash')],
            },
        ),
        migrations.CreateModel(
            name='OfficePayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payout_accounts', to='organizations.office')),
                ('method_type', models.CharField(choices=[('bank', 'Bank'), ('wallet', 'Wallet'), ('cash_clearing', 'Cash clearing')], max_length=30)),
                ('account_holder_name', models.CharField(max_length=200)),
                ('account_reference_ciphertext', models.BinaryField()),
                ('account_reference_last4', models.CharField(blank=True, max_length=8, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('active', 'Active'), ('suspended', 'Suspended'), ('replaced', 'Replaced')], default='pending', max_length=24)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_payout_accounts', to='identity.user')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_payout_accounts', to='identity.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'office_payout_accounts',
                'constraints': [models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='ck_payout_dual_approval'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('office',), name='uq_active_payout_account')],
                'indexes': [],
            },
        ),
    ]
