# Generated by Django 5.2.16 on 2026-07-21 18:08

import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminops', '0001_initial'),
        ('identity', '0003_platformroleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformActionApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('action_type', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=60)),
                ('target_id', models.UUIDField()),
                ('payload', models.JSONField(default=dict)),
                ('risk_level', models.CharField(default='critical', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_platform_approvals', to='identity.user')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requested_platform_approvals', to='identity.user')),
            ],
            options={
                'db_table': 'platform_action_approvals',
                'indexes': [models.Index(fields=['status', 'action_type', 'requested_at'], name='ix_platform_approval_queue'), models.Index(fields=['target_type', 'target_id'], name='ix_platform_approval_target')],
                'constraints': [models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('requested_by')), _negated=True), _connector='OR'), name='ck_platform_approval_dual_control')],
            },
        ),
    ]
