# Generated by Django 5.2.16 on 2026-07-21 21:14

import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0003_platformroleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadTestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('scenario', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('requests', models.PositiveIntegerField(default=0)),
                ('error_rate_percent', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('p95_ms', models.PositiveIntegerField(default=0)),
                ('duplicate_seats', models.PositiveIntegerField(default=0)),
                ('duplicate_financial_entries', models.PositiveIntegerField(default=0)),
                ('slo_json', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'load_test_runs',
            },
        ),
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='started', max_length=20)),
                ('backup_type', models.CharField(default='full', max_length=30)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_wal_at', models.DateTimeField(blank=True, null=True)),
                ('artifact_uri', models.CharField(blank=True, max_length=500)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'backup_runs',
                'indexes': [models.Index(fields=['status', 'started_at'], name='ix_backup_run_status')],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('severity', models.CharField(choices=[('SEV1', 'SEV-1'), ('SEV2', 'SEV-2'), ('SEV3', 'SEV-3')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('communication_channel', models.CharField(max_length=240)),
                ('customer_impact', models.TextField(blank=True)),
                ('postmortem', models.TextField(blank=True)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='commanded_incidents', to='identity.user')),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='IncidentTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('event_type', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='identity.user')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='continuity.incident')),
            ],
            options={
                'db_table': 'incident_timeline_entries',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformContinuityState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singleton_key', models.CharField(default='platform', max_length=20, unique=True)),
                ('mode', models.CharField(choices=[('normal', 'Normal'), ('maintenance', 'Maintenance'), ('recovery', 'Recovery'), ('reconciliation', 'Reconciliation')], default='normal', max_length=24)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('reconciliation_required', models.BooleanField(default=False)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='continuity_changes', to='identity.user')),
            ],
            options={
                'db_table': 'platform_continuity_state',
            },
        ),
        migrations.CreateModel(
            name='RecoveryExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_time', models.DateTimeField()),
                ('restored_to_time', models.DateTimeField(blank=True, null=True)),
                ('rpo_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rto_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_json', models.JSONField(default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recovery_exercises', to='continuity.backuprun')),
            ],
            options={
                'db_table': 'recovery_exercises',
            },
        ),
        migrations.CreateModel(
            name='ReleaseRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('version', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='running', max_length=20)),
                ('health_passed', models.BooleanField(default=False)),
                ('smoke_passed', models.BooleanField(default=False)),
                ('rollback_required', models.BooleanField(default=False)),
                ('rollback_reference', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_json', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'release_runs',
                'indexes': [models.Index(fields=['status', 'started_at'], name='ix_release_status')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('seat_conflicts', models.PositiveIntegerField(default=0)),
                ('payment_conflicts', models.PositiveIntegerField(default=0)),
                ('ledger_conflicts', models.PositiveIntegerField(default=0)),
                ('evidence_json', models.JSONField(default=dict)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reconciliation_runs', to='identity.user')),
            ],
            options={
                'db_table': 'reconciliation_runs',
                'indexes': [models.Index(fields=['status', 'started_at'], name='ix_reconciliation_status')],
            },
        ),
    ]
