# Generated by Django 5.2.16 on 2026-07-20 23:31

import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('location_type', models.CharField(choices=[('city', 'City'), ('garage', 'Garage'), ('boarding_point', 'Boarding point'), ('dropoff_point', 'Drop-off point')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='geography.location')),
                ('name_ar', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160, null=True)),
                ('address_text', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['name_ar', 'public_id'],
                'indexes': [models.Index(fields=['location_type', 'status'], name='ix_location_type_status'), models.Index(fields=['parent', 'status'], name='ix_location_parent_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='ck_location_latitude'), models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='ck_location_longitude')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('origin_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='origin_routes', to='geography.location')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destination_routes', to='geography.location')),
                ('name_ar', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['name_ar', 'public_id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ix_route_status_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('origin_location', models.F('destination_location')), _negated=True), name='ck_route_distinct_endpoints'), models.UniqueConstraint(fields=('origin_location', 'destination_location'), name='uq_route_direction')],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='geography.route')),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='route_stops', to='geography.location')),
                ('stop_type', models.CharField(choices=[('boarding', 'Boarding'), ('dropoff', 'Drop-off'), ('both', 'Both')], max_length=20)),
                ('offset_minutes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'route_stops',
                'ordering': ['sequence_no'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sequence_no__gt', 0)), name='ck_route_stop_sequence'), models.UniqueConstraint(fields=('route', 'sequence_no'), name='pk_route_stops'), models.UniqueConstraint(fields=('route', 'location'), name='uq_route_stop_location')],
                'indexes': [],
            },
        ),
    ]
