# Generated by Django 5.2.16 on 2026-07-20 23:58

import bookings.models
import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_session_mfa_evidence'),
        ('organizations', '0002_verification_branches_and_payouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('full_name', models.CharField(max_length=160)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=12)),
                ('passenger_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant')], default='adult', max_length=16)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality_code', models.CharField(blank=True, max_length=2, null=True)),
                ('identity_type', models.CharField(blank=True, max_length=24, null=True)),
                ('identity_number_normalized', models.CharField(blank=True, max_length=80, null=True)),
                ('boarding_status', models.CharField(choices=[('not_arrived', 'Not arrived'), ('arrived', 'Arrived'), ('verified', 'Verified'), ('boarded', 'Boarded'), ('boarded_reversed', 'Boarded reversed'), ('denied', 'Denied'), ('no_show', 'No-show')], default='not_arrived', max_length=28)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_passengers',
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('moved', 'Moved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seat_assignments',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('pnr', models.CharField(default=bookings.models.generate_pnr, editable=False, max_length=12, unique=True)),
                ('source', models.CharField(choices=[('public_web', 'Public web'), ('office', 'Office'), ('phone', 'Phone'), ('import', 'Import')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('cancellation_pending', 'Cancellation pending'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No-show'), ('denied_boarding_review', 'Denied boarding review')], default='draft', max_length=32)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_verification', 'Pending verification'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='unpaid', max_length=24)),
                ('contact_name', models.CharField(max_length=160)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('pricing_snapshot', models.JSONField(default=dict)),
                ('commission_snapshot', models.JSONField(default=dict)),
                ('terms_version_ids', models.JSONField(default=list)),
                ('manage_token_hash', models.BinaryField(unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='organizations.officebranch')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_bookings', to='identity.user')),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='identity.user')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='organizations.office')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
