# Generated by Django 5.2.16 on 2026-07-20 23:58

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='passengers', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seat_assignments', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seat_assignments', to='bookings.bookingpassenger'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='supersedes', to='bookings.seatassignment'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seat_assignments', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='seatassignment',
            name='trip_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='trips.tripseat'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['office', '-created_at'], name='ix_booking_office_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['trip', 'status'], name='ix_booking_trip_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['contact_phone'], name='ix_booking_contact_phone'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0), ('discount_amount__gte', 0), ('fee_amount__gte', 0), ('total_amount__gte', 0)), name='ck_booking_nonnegative_totals'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_amount'), '-', models.F('discount_amount')), '+', models.F('fee_amount')))), name='ck_booking_total_formula'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0), ('refunded_amount__gte', 0), ('refunded_amount__lte', models.F('paid_amount'))), name='ck_booking_payment_totals'),
        ),
        migrations.AddConstraint(
            model_name='bookingpassenger',
            constraint=models.UniqueConstraint(fields=('booking', 'sequence_no'), name='uq_booking_passenger_sequence'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('trip', 'trip_seat'), name='uq_active_seat_assignment'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('passenger',), name='uq_active_passenger_assignment'),
        ),
        migrations.AddConstraint(
            model_name='seatassignment',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__gte', 0)), name='ck_assignment_price'),
        ),
    ]
