# Generated by Django 5.2.16 on 2026-07-21 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('identity', '0002_session_mfa_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpassenger',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingpassenger',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=16),
        ),
        migrations.CreateModel(
            name='BookingChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('passenger_replaced', 'Passenger replaced'), ('seat_changed', 'Seat changed'), ('passenger_cancelled', 'Passenger cancelled'), ('booking_cancelled', 'Booking cancelled')], max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=80, null=True)),
                ('before_snapshot', models.JSONField(default=dict)),
                ('after_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='changes', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='booking_changes', to='identity.user')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='changes', to='bookings.bookingpassenger')),
            ],
            options={
                'db_table': 'booking_changes',
                'indexes': [models.Index(fields=['booking', '-created_at'], name='ix_booking_change_created')],
            },
        ),
    ]
