# Generated by Django 5.2.16 on 2026-07-20 23:58

import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('fleet', '0001_initial'),
        ('geography', '0001_initial'),
        ('identity', '0002_session_mfa_evidence'),
        ('organizations', '0002_verification_branches_and_payouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('booking_open', 'Booking open'), ('boarding_open', 'Boarding open'), ('boarding_closed', 'Boarding closed'), ('departed', 'Departed'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted')], default='draft', max_length=24)),
                ('scheduled_departure_at', models.DateTimeField()),
                ('scheduled_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_at', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('booking_open_at', models.DateTimeField(blank=True, null=True)),
                ('booking_close_at', models.DateTimeField(blank=True, null=True)),
                ('boarding_open_at', models.DateTimeField(blank=True, null=True)),
                ('boarding_close_at', models.DateTimeField(blank=True, null=True)),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('pricing_snapshot', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='organizations.officebranch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_trips', to='identity.user')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='fleet.driver')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='organizations.office')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='organizations.transportoperator')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='geography.route')),
                ('seat_layout', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='fleet.seatlayout')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['scheduled_departure_at', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='TripCancellationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('alternative_offered', 'Alternative offered'), ('refund_started', 'Refund started'), ('resolved', 'Resolved')], default='pending', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_cancellation_actions', to='bookings.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cancellation_actions', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_cancellation_actions',
            },
        ),
        migrations.CreateModel(
            name='TripChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('time', 'Time'), ('price', 'Price'), ('vehicle', 'Vehicle'), ('route', 'Route'), ('multiple', 'Multiple')], max_length=20)),
                ('classification', models.CharField(choices=[('minor', 'Minor'), ('material', 'Material')], max_length=20)),
                ('previous_snapshot', models.JSONField(default=dict)),
                ('new_snapshot', models.JSONField(default=dict)),
                ('response_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_changes', to='identity.user')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='changes', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripChangeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('alternative_requested', 'Alternative requested'), ('refund_requested', 'Refund requested'), ('resolved', 'Resolved')], default='pending', max_length=28)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_change_responses', to='bookings.booking')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='trips.tripchange')),
            ],
            options={
                'db_table': 'trip_change_responses',
            },
        ),
        migrations.CreateModel(
            name='TripOperationalIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('urgent_case', 'Urgent case'), ('manifest_unbalanced', 'Manifest unbalanced'), ('vehicle_unavailable', 'Vehicle unavailable'), ('driver_unavailable', 'Driver unavailable')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operational_issues', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_operational_issues',
            },
        ),
        migrations.CreateModel(
            name='TripSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_code', models.CharField(max_length=12)),
                ('seat_type', models.CharField(max_length=20)),
                ('sellable', models.BooleanField(default=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=160, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('layout_seat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_seats', to='fleet.seatlayoutseat')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seats', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_seats',
                'ordering': ['layout_seat__row_no', 'layout_seat__column_no', 'seat_code'],
            },
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hold_token_hash', models.BinaryField(unique=True)),
                ('owner_booking_draft_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('consumed', 'Consumed'), ('expired', 'Expired'), ('released', 'Released')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('owner_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='seat_holds', to='identity.usersession')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seat_holds', to='trips.trip')),
                ('trip_seat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='holds', to='trips.tripseat')),
            ],
            options={
                'db_table': 'seat_holds',
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_no', models.PositiveSmallIntegerField()),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('stop_type', models.CharField(choices=[('boarding', 'Boarding'), ('dropoff', 'Drop-off'), ('both', 'Both')], max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_stops', to='geography.location')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stops', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_stops',
                'ordering': ['sequence_no'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'scheduled_departure_at', 'status'], name='ix_trip_search'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['office', 'scheduled_departure_at'], name='ix_trip_office_departure'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_arrival_at__isnull', True), ('scheduled_arrival_at__gt', models.F('scheduled_departure_at')), _connector='OR'), name='ck_trip_arrival_after_departure'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='ck_trip_base_price'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('booking_close_at__isnull', True), ('booking_close_at__lte', models.F('scheduled_departure_at')), _connector='OR'), name='ck_trip_booking_close_before_departure'),
        ),
        migrations.AddConstraint(
            model_name='tripcancellationaction',
            constraint=models.UniqueConstraint(fields=('trip', 'booking'), name='uq_trip_cancellation_booking'),
        ),
        migrations.AddConstraint(
            model_name='tripchangeresponse',
            constraint=models.UniqueConstraint(fields=('change', 'booking'), name='uq_trip_change_booking'),
        ),
        migrations.AddIndex(
            model_name='tripoperationalissue',
            index=models.Index(fields=['trip', 'status'], name='ix_trip_issue_status'),
        ),
        migrations.AddIndex(
            model_name='tripseat',
            index=models.Index(fields=['trip', 'sellable'], name='ix_trip_seat_sellable'),
        ),
        migrations.AddConstraint(
            model_name='tripseat',
            constraint=models.UniqueConstraint(fields=('trip', 'layout_seat'), name='uq_trip_layout_seat'),
        ),
        migrations.AddConstraint(
            model_name='tripseat',
            constraint=models.UniqueConstraint(fields=('trip', 'seat_code'), name='uq_trip_seat_code'),
        ),
        migrations.AddConstraint(
            model_name='seathold',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='ck_hold_expiry'),
        ),
        migrations.AddConstraint(
            model_name='seathold',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('trip_seat',), name='uq_active_hold_per_seat'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip', 'sequence_no'), name='uq_trip_stop_sequence'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip', 'location'), name='uq_trip_stop_location'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_no__gt', 0)), name='ck_trip_stop_sequence'),
        ),
    ]
