# Generated by Django 5.2.16 on 2026-07-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_session_mfa_evidence'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['expires_at'], name='ix_hold_expiry'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['owner_booking_draft_id', 'status'], name='ix_hold_batch_status'),
        ),
    ]
