# Generated by Django 5.2.16 on 2026-07-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_seathold_ix_hold_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seathold',
            name='quote_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='seathold',
            name='quote_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
