# Generated by Django 5.2.16 on 2026-07-21 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingpassenger_cancelled_at_and_more'),
        ('fleet', '0001_initial'),
        ('identity', '0002_session_mfa_evidence'),
        ('trips', '0003_seathold_quote_snapshot_seathold_quote_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripInterruptionResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('service_completed', 'Service completed'), ('alternative_accepted', 'Alternative accepted'), ('refund_started', 'Refund started'), ('compensated', 'Compensated')], default='pending', max_length=28)),
                ('resolution_details', models.JSONField(default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trip_interruption_resolutions',
            },
        ),
        migrations.CreateModel(
            name='TripReallocationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_seat_code', models.CharField(max_length=12)),
                ('old_seat_type', models.CharField(max_length=20)),
                ('target_seat_code', models.CharField(blank=True, max_length=12, null=True)),
                ('target_seat_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('conflict', 'Conflict'), ('applied', 'Applied')], default='proposed', max_length=20)),
                ('conflict_code', models.CharField(blank=True, max_length=80, null=True)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'trip_reallocation_lines',
                'ordering': ['passenger__booking__pnr', 'passenger__sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='TripReallocationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_version', models.PositiveIntegerField()),
                ('source_inventory_version', models.PositiveIntegerField()),
                ('target_inventory_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('conflicted', 'Conflicted'), ('applied', 'Applied'), ('superseded', 'Superseded')], default='previewed', max_length=20)),
                ('simulation', models.JSONField(default=dict)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trip_reallocation_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='tripseat',
            name='uq_trip_layout_seat',
        ),
        migrations.RemoveConstraint(
            model_name='tripseat',
            name='uq_trip_seat_code',
        ),
        migrations.RemoveIndex(
            model_name='tripseat',
            name='ix_trip_seat_sellable',
        ),
        migrations.AddField(
            model_name='tripseat',
            name='inventory_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tripseat',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='tripseat',
            index=models.Index(fields=['trip', 'is_current', 'sellable'], name='ix_trip_current_sellable'),
        ),
        migrations.AddIndex(
            model_name='tripseat',
            index=models.Index(fields=['trip', 'inventory_version'], name='ix_trip_inventory_version'),
        ),
        migrations.AddConstraint(
            model_name='tripseat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('trip', 'layout_seat'), name='uq_current_trip_layout_seat'),
        ),
        migrations.AddConstraint(
            model_name='tripseat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('trip', 'seat_code'), name='uq_current_trip_seat_code'),
        ),
        migrations.AddField(
            model_name='tripinterruptionresolution',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_interruption_resolutions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='tripinterruptionresolution',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='resolved_trip_interruptions', to='identity.user'),
        ),
        migrations.AddField(
            model_name='tripinterruptionresolution',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interruption_resolutions', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripreallocationline',
            name='old_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_reallocation_lines', to='bookings.seatassignment'),
        ),
        migrations.AddField(
            model_name='tripreallocationline',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_reallocation_lines', to='bookings.bookingpassenger'),
        ),
        migrations.AddField(
            model_name='tripreallocationline',
            name='target_layout_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='trip_reallocation_lines', to='fleet.seatlayoutseat'),
        ),
        migrations.AddField(
            model_name='tripreallocationplan',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='applied_trip_reallocation_plans', to='identity.user'),
        ),
        migrations.AddField(
            model_name='tripreallocationplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_trip_reallocation_plans', to='identity.user'),
        ),
        migrations.AddField(
            model_name='tripreallocationplan',
            name='previous_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='previous_trip_reallocation_plans', to='fleet.seatlayout'),
        ),
        migrations.AddField(
            model_name='tripreallocationplan',
            name='previous_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='previous_trip_reallocation_plans', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='tripreallocationplan',
            name='target_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='target_trip_reallocation_plans', to='fleet.seatlayout'),
        ),
        migrations.AddField(
            model_name='tripreallocationplan',
            name='target_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='target_trip_reallocation_plans', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='tripreallocationplan',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reallocation_plans', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='tripreallocationline',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lines', to='trips.tripreallocationplan'),
        ),
        migrations.AddIndex(
            model_name='tripinterruptionresolution',
            index=models.Index(fields=['trip', 'status'], name='ix_trip_interruption_status'),
        ),
        migrations.AddConstraint(
            model_name='tripinterruptionresolution',
            constraint=models.UniqueConstraint(fields=('trip', 'booking'), name='uq_trip_interruption_booking'),
        ),
        migrations.AddIndex(
            model_name='tripreallocationplan',
            index=models.Index(fields=['trip', 'status', '-created_at'], name='ix_trip_reallocation_status'),
        ),
        migrations.AddConstraint(
            model_name='tripreallocationline',
            constraint=models.UniqueConstraint(fields=('plan', 'passenger'), name='uq_reallocation_plan_passenger'),
        ),
        migrations.AddConstraint(
            model_name='tripreallocationline',
            constraint=models.UniqueConstraint(condition=models.Q(('target_layout_seat__isnull', False)), fields=('plan', 'target_layout_seat'), name='uq_reallocation_plan_target_seat'),
        ),
    ]
