# Generated by Django 5.2.16 on 2026-07-21 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_bookingpassenger_cancelled_at_and_more'),
        ('identity', '0002_session_mfa_evidence'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=20)),
                ('language', models.CharField(default='ar', max_length=5)),
                ('version', models.PositiveIntegerField(default=1)),
                ('subject_template', models.CharField(blank=True, max_length=240)),
                ('body_template', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='published', max_length=20)),
                ('effective_from', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['code', 'channel', 'language', '-version'],
                'indexes': [models.Index(fields=['code', 'channel', 'language', 'status', '-effective_from'], name='ix_notif_tpl_lookup')],
                'constraints': [models.UniqueConstraint(fields=('code', 'channel', 'language', 'version'), name='uq_notification_template_version')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_event_id', models.UUIDField()),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('recipient_type', models.CharField(choices=[('user', 'User'), ('office', 'Office'), ('booking_contact', 'Booking contact')], max_length=20)),
                ('recipient_id', models.UUIDField(blank=True, null=True)),
                ('language', models.CharField(default='ar', max_length=5)),
                ('payload', models.JSONField(default=dict)),
                ('rendered_subject', models.CharField(blank=True, max_length=240)),
                ('rendered_body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('partially_sent', 'Partially sent'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('action_required', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='bookings.booking')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notifications', to='notifications.notificationtemplate')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=20)),
                ('token_hash', models.BinaryField(unique=True)),
                ('token_ciphertext', models.BinaryField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('invalid', 'Invalid')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='push_subscriptions', to='identity.userdevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='push_subscriptions', to='identity.user')),
            ],
            options={
                'db_table': 'push_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=20)),
                ('destination_hash', models.BinaryField(blank=True, null=True)),
                ('destination_ciphertext', models.BinaryField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=160, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80, null=True)),
                ('permanent_failure', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_deliveries',
                'ordering': ['notification', 'channel', 'attempt_no'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='ix_notif_delivery_due'), models.Index(fields=['notification', 'channel', '-attempt_no'], name='ix_notif_delivery_hist')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'channel', 'attempt_no'), name='uq_notification_delivery_attempt')],
            },
        ),
        migrations.CreateModel(
            name='NotificationEscalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='escalation', to='notifications.notification')),
                ('support_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notification_escalations', to='support.supportcase')),
            ],
            options={
                'db_table': 'notification_escalations',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('status', 'open')), models.Q(('resolved_at__isnull', False), ('status', 'resolved')), _connector='OR'), name='ck_notification_escalation_resolution')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notification_preferences', to='identity.user')),
            ],
            options={
                'db_table': 'notification_preferences',
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type', 'channel'), name='uq_notification_preference')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_type', 'recipient_id', '-created_at'], name='ix_notif_recipient'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', '-created_at'], name='ix_notif_status'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['booking', '-created_at'], name='ix_notif_booking'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'status'], name='ix_push_user_state'),
        ),
    ]
