# Generated by Django 5.2.16 on 2026-07-20 22:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(max_length=30)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('key', models.CharField(max_length=120)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idempotency_keys',
                'constraints': [models.UniqueConstraint(fields=('scope_type', 'scope_id', 'key'), name='uq_idempotency_scope_key')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox_events',
                'indexes': [models.Index(fields=['published_at', 'next_attempt_at'], name='ix_outbox_pending')],
            },
        ),
    ]
