# Generated by Django 5.2.16 on 2026-07-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='scope_type',
            field=models.CharField(max_length=80),
        ),
    ]
