# Generated by Django 5.2.16 on 2026-07-21 09:51

import boarding.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_bookingpassenger_cancelled_at_and_more'),
        ('identity', '0002_session_mfa_evidence'),
        ('tickets', '0001_initial'),
        ('trips', '0003_seathold_quote_snapshot_seathold_quote_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingCorrectionApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('used', 'Used'), ('revoked', 'Revoked')], default='approved', max_length=20)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='approved_boarding_corrections', to='identity.user')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='boarding_correction_approvals', to='bookings.bookingpassenger')),
            ],
            options={
                'db_table': 'boarding_correction_approvals',
            },
        ),
        migrations.CreateModel(
            name='TripManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('boarding_closed', 'Boarding closed'), ('final', 'Final')], max_length=20)),
                ('manifest_json', models.JSONField()),
                ('sha256', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='generated_trip_manifests', to='identity.user')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='manifests', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_manifests',
                'ordering': ['-version_no'],
            },
            bases=(boarding.models.ImmutableRecordMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OfflineBoardingPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_version', models.PositiveIntegerField()),
                ('package_hash', models.CharField(max_length=64, unique=True)),
                ('ciphertext', models.BinaryField()),
                ('signature', models.BinaryField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_offline_boarding_packages', to='identity.user')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offline_boarding_packages', to='identity.userdevice')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offline_packages', to='trips.trip')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='offline_packages', to='boarding.tripmanifest')),
            ],
            options={
                'db_table': 'offline_boarding_packages',
            },
        ),
        migrations.CreateModel(
            name='BoardingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('arrived', 'Arrived'), ('verified', 'Verified'), ('boarded', 'Boarded'), ('reversed', 'Reversed'), ('denied', 'Denied'), ('no_show', 'No-show'), ('manual_check', 'Manual check')], max_length=24)),
                ('occurred_at', models.DateTimeField()),
                ('offline_event_id', models.CharField(blank=True, max_length=80, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=80, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='boarding_events', to='identity.user')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='boarding_events', to='identity.userdevice')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='boarding_events', to='bookings.bookingpassenger')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='boarding_events', to='tickets.ticket')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='boarding_events', to='trips.trip')),
            ],
            options={
                'db_table': 'boarding_events',
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['trip', 'occurred_at'], name='ix_board_event_trip_time'), models.Index(fields=['passenger', 'occurred_at'], name='ix_board_event_pass_time')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('offline_event_id__isnull', False)), fields=('device', 'offline_event_id'), name='uq_boarding_device_offline_event')],
            },
            bases=(boarding.models.ImmutableRecordMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BoardingSyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offline_event_id', models.CharField(max_length=80)),
                ('conflict_type', models.CharField(max_length=80)),
                ('event_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='boarding_sync_conflicts', to='bookings.bookingpassenger')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='boarding_sync_conflicts', to='tickets.ticket')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conflicts', to='boarding.offlineboardingpackage')),
            ],
            options={
                'db_table': 'boarding_sync_conflicts',
                'indexes': [models.Index(fields=['package', 'status'], name='ix_offline_conflict_status')],
                'constraints': [models.UniqueConstraint(fields=('package', 'offline_event_id'), name='uq_offline_package_conflict_event')],
            },
        ),
        migrations.AddIndex(
            model_name='tripmanifest',
            index=models.Index(fields=['trip', '-version_no'], name='ix_manifest_trip_version'),
        ),
        migrations.AddConstraint(
            model_name='tripmanifest',
            constraint=models.UniqueConstraint(fields=('trip', 'version_no'), name='uq_trip_manifest_version'),
        ),
        migrations.AddIndex(
            model_name='offlineboardingpackage',
            index=models.Index(fields=['trip', 'expires_at'], name='ix_offline_pkg_trip_expiry'),
        ),
    ]
