# Generated by Django 5.2.16 on 2026-07-21 08:39

import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('identity', '0002_session_mfa_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('method_type', models.CharField(choices=[('office_cash', 'Office cash'), ('manual_transfer', 'Manual transfer'), ('electronic', 'Electronic')], max_length=24)),
                ('status', models.CharField(choices=[('created', 'Created'), ('requires_action', 'Requires action'), ('pending_verification', 'Pending verification'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='created', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('provider_code', models.CharField(blank=True, max_length=60, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=160, null=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('provider_action', models.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment_intents', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_payment_intents', to='identity.user')),
            ],
            options={
                'db_table': 'payment_intents',
            },
        ),
        migrations.CreateModel(
            name='ManualPaymentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_reference', models.CharField(blank=True, max_length=160, null=True)),
                ('transfer_reference', models.CharField(max_length=160, unique=True)),
                ('transferred_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('proof_object_key', models.TextField(blank=True, null=True)),
                ('proof_sha256', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reviewed_manual_payments', to='identity.user')),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='manual_submissions', to='payments.paymentintent')),
            ],
            options={
                'db_table': 'manual_payment_submissions',
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=80)),
                ('resolution_required', models.CharField(choices=[('refund_or_alternative', 'Refund or alternative'), ('amount_currency_review', 'Amount/currency review'), ('overpayment_refund', 'Overpayment refund')], max_length=40)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expected_currency', models.CharField(max_length=3)),
                ('received_currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment_reconciliation_cases', to='bookings.booking')),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reconciliation_cases', to='payments.paymentintent')),
            ],
            options={
                'db_table': 'payment_reconciliation_cases',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('authorize', 'Authorize'), ('capture', 'Capture'), ('payment', 'Payment'), ('reversal', 'Reversal')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('reversed', 'Reversed')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('provider_event_id', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('receipt_number', models.CharField(blank=True, max_length=120, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_reference_hash', models.BinaryField(blank=True, null=True, unique=True)),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='payments.paymentintent')),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_code', models.CharField(max_length=60)),
                ('provider_event_id', models.CharField(max_length=160)),
                ('event_type', models.CharField(max_length=120)),
                ('signature_valid', models.BooleanField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'indexes': [models.Index(fields=['status', 'received_at'], name='ix_webhook_delivery_queue')],
                'constraints': [models.UniqueConstraint(fields=('provider_code', 'provider_event_id'), name='uq_webhook_provider_event')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['booking', 'status'], name='ix_pay_intent_booking_status'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['expires_at', 'status'], name='ix_pay_intent_expiry'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(fields=('booking', 'idempotency_key'), name='uq_booking_payment_intent_key'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference__isnull', False)), fields=('provider_code', 'provider_reference'), name='uq_payment_provider_reference'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_intent_amount'),
        ),
        migrations.AddIndex(
            model_name='manualpaymentsubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='ix_manual_pay_review_queue'),
        ),
        migrations.AddConstraint(
            model_name='manualpaymentsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_manual_payment_amount'),
        ),
        migrations.AddIndex(
            model_name='paymentreconciliationcase',
            index=models.Index(fields=['status', 'reason_code'], name='ix_pay_recon_queue'),
        ),
        migrations.AddConstraint(
            model_name='paymentreconciliationcase',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('payment_intent', 'reason_code'), name='uq_open_reconciliation_reason'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_intent', 'status'], name='ix_pay_tx_intent_status'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_payment_tx_amount'),
        ),
    ]
