# Generated by Django 5.2.16 on 2026-07-21 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingpassenger_cancelled_at_and_more'),
        ('identity', '0002_session_mfa_evidence'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargeback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_case_id', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('evidence_submitted', 'Evidence submitted'), ('won', 'Won'), ('lost', 'Lost'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='open', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chargebacks', to='payments.paymenttransaction')),
            ],
            options={
                'db_table': 'chargebacks',
                'indexes': [models.Index(fields=['status', 'deadline_at'], name='ix_chargeback_status_deadline')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_chargeback_amount')],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under review'), ('approved', 'Approved'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=24)),
                ('reason_code', models.CharField(max_length=80)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('provider_reference', models.CharField(blank=True, max_length=160, null=True)),
                ('quote_snapshot', models.JSONField(default=dict)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_refunds', to='identity.user')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='bookings.booking')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='bookings.bookingpassenger')),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='refunds', to='payments.paymentintent')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requested_refunds', to='identity.user')),
            ],
            options={
                'db_table': 'refunds',
                'indexes': [models.Index(fields=['booking', 'status'], name='ix_refund_booking_status'), models.Index(fields=['status', 'created_at'], name='ix_refund_review_queue')],
                'constraints': [models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='ck_refund_requested_positive'), models.CheckConstraint(condition=models.Q(('approved_amount__isnull', True), models.Q(('approved_amount__gte', 0), ('approved_amount__lte', models.F('requested_amount'))), _connector='OR'), name='ck_refund_approved_range'), models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('requested_by')), _negated=True), _connector='OR'), name='ck_refund_dual_approval'), models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'under_review', 'approved', 'processing'])), fields=('booking', 'passenger'), name='uq_open_refund_booking_passenger')],
            },
        ),
    ]
