# Generated by Django 5.2.16 on 2026-07-21 19:10

import common.ids
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0004_financialdispute_appeal_deadline_at_and_more'),
        ('identity', '0003_platformroleassignment'),
        ('organizations', '0002_verification_branches_and_payouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('grace', 'Grace'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=24)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('price_snapshot', models.JSONField()),
                ('features_snapshot', models.JSONField(default=dict)),
                ('limits_snapshot', models.JSONField(default=dict)),
                ('auto_renew', models.BooleanField(default=False)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('source', models.CharField(default='platform', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='organizations.office')),
            ],
            options={
                'db_table': 'office_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name_ar', models.CharField(max_length=160)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('features_json', models.JSONField(default=dict)),
                ('limits_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_subscription_plans', to='identity.user')),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('effective_mode', models.CharField(choices=[('immediate', 'Immediate'), ('next_period', 'Next period')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('current_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='change_requests', to='subscriptions.officesubscription')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscription_changes', to='organizations.office')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscription_change_requests', to='identity.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reviewed_subscription_changes', to='identity.user')),
                ('requested_plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='change_requests', to='subscriptions.subscriptionplan')),
            ],
            options={
                'db_table': 'subscription_change_requests',
            },
        ),
        migrations.AddField(
            model_name='officesubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='office_subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], default='open', max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('due_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subscription_invoice_entries', to='finance.ledgerentry')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscription_invoices', to='organizations.office')),
                ('office_subscription', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invoices', to='subscriptions.officesubscription')),
                ('payment_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='subscription_payment_entries', to='finance.ledgerentry')),
            ],
            options={
                'db_table': 'subscription_invoices',
                'indexes': [models.Index(fields=['office', 'status', 'due_at'], name='ix_subscription_invoice_due')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0), ('tax_amount__gte', 0), ('total_amount', django.db.models.expressions.CombinedExpression(models.F('subtotal_amount'), '+', models.F('tax_amount')))), name='ck_subscription_invoice_totals')],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['status', 'effective_from'], name='ix_subscription_plan_active'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__gte', 0)), name='ck_subscription_plan_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_subscription_plan_effective_window'),
        ),
        migrations.AddIndex(
            model_name='subscriptionchangerequest',
            index=models.Index(fields=['office', 'status', 'requested_at'], name='ix_subscription_change_queue'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionchangerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('office',), name='uq_pending_subscription_change'),
        ),
        migrations.AddIndex(
            model_name='officesubscription',
            index=models.Index(fields=['office', 'status', 'period_end'], name='ix_office_subscription_current'),
        ),
        migrations.AddIndex(
            model_name='officesubscription',
            index=models.Index(fields=['status', 'period_end'], name='ix_subscription_due'),
        ),
        migrations.AddConstraint(
            model_name='officesubscription',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='ck_subscription_period'),
        ),
        migrations.AddConstraint(
            model_name='officesubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['trial', 'active', 'past_due', 'grace'])), fields=('office',), name='uq_active_subscription'),
        ),
    ]
