# Generated by Django 5.2.16 on 2026-07-21 10:51

import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_bookingpassenger_cancelled_at_and_more'),
        ('identity', '0002_session_mfa_evidence'),
        ('organizations', '0002_verification_branches_and_payouts'),
        ('trips', '0003_seathold_quote_snapshot_seathold_quote_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], default='P3', max_length=8)),
                ('category', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('awaiting_customer', 'Awaiting customer'), ('awaiting_office', 'Awaiting office'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=24)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_code', models.CharField(blank=True, max_length=80, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='support_cases', to='bookings.booking')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='support_cases', to='organizations.office')),
                ('opened_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='opened_support_cases', to='identity.user')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='owned_support_cases', to='identity.user')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='support_cases', to='trips.trip')),
            ],
            options={
                'db_table': 'support_cases',
                'ordering': ['priority', 'sla_due_at', 'opened_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('severity', models.CharField(default='P1', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed')], default='open', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='violations', to='organizations.office')),
                ('support_case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='violations', to='support.supportcase')),
            ],
            options={
                'db_table': 'office_violations',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('office', 'Office'), ('platform', 'Platform'), ('system', 'System')], max_length=20)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('shared', 'Shared'), ('internal', 'Internal')], default='shared', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='messages', to='support.supportcase')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='support_messages', to='identity.user')),
            ],
            options={
                'db_table': 'support_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['office', 'status', 'priority'], name='ix_support_office_queue'),
        ),
        migrations.AddIndex(
            model_name='supportcase',
            index=models.Index(fields=['status', 'sla_due_at'], name='ix_support_sla_due'),
        ),
        migrations.AddConstraint(
            model_name='supportcase',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['P0', 'P1', 'P2', 'P3', 'P4'])), name='ck_support_priority'),
        ),
        migrations.AddIndex(
            model_name='officeviolation',
            index=models.Index(fields=['office', 'status'], name='ix_violation_office_status'),
        ),
        migrations.AddConstraint(
            model_name='officeviolation',
            constraint=models.UniqueConstraint(fields=('support_case', 'code'), name='uq_support_case_violation_code'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['case', 'created_at'], name='ix_support_message_case'),
        ),
    ]
