# Generated by Django 5.2.16 on 2026-07-20 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_type', models.CharField(max_length=20)),
                ('office_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('ip_hash', models.BinaryField(blank=True, null=True)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=80, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='audit_events', to='identity.user')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['occurred_at'], name='ix_audit_time')],
            },
        ),
    ]
