# Generated by Django 5.2.16 on 2026-07-21 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('organizations', '0002_verification_branches_and_payouts'),
        ('trips', '0003_seathold_quote_snapshot_seathold_quote_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('contra', 'Contra')], max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_accounts', to='organizations.office')),
            ],
            options={
                'db_table': 'ledger_accounts',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('event_id', models.UUIDField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], default='posted', max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='bookings.booking')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='organizations.office')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reversals', to='finance.ledgerentry')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='trips.trip')),
            ],
            options={
                'db_table': 'ledger_entries',
            },
        ),
        migrations.CreateModel(
            name='LedgerPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('memo', models.CharField(blank=True, max_length=240, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='postings', to='finance.ledgeraccount')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='postings', to='finance.ledgerentry')),
            ],
            options={
                'db_table': 'ledger_postings',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('pending', 'Pending'), ('earned', 'Earned'), ('in_settlement', 'In settlement'), ('paid', 'Paid'), ('reversed', 'Reversed'), ('adjusted', 'Adjusted')], default='expected', max_length=24)),
                ('basis_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='commission', to='bookings.booking')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='commissions', to='organizations.office')),
            ],
            options={
                'db_table': 'commissions',
                'constraints': [models.CheckConstraint(condition=models.Q(('basis_amount__gte', 0), ('rate__gte', 0), ('fixed_amount__gte', 0), ('commission_amount__gte', 0)), name='ck_commission_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('office__isnull', False)), fields=('office', 'code', 'currency'), name='uq_office_ledger_account'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('office__isnull', True)), fields=('code', 'currency'), name='uq_global_ledger_account'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('event_type', 'event_id', 'currency'), name='uq_ledger_event_currency'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('reversal_of__isnull', True), ('status', 'reversed'), _connector='OR'), name='ck_ledger_reversal_status'),
        ),
        migrations.AddConstraint(
            model_name='ledgerposting',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_ledger_posting_positive'),
        ),
    ]
