# Generated by Django 5.2.16 on 2026-07-21 11:39

import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingpassenger_cancelled_at_and_more'),
        ('finance', '0002_ledger_balance_trigger'),
        ('identity', '0002_session_mfa_evidence'),
        ('organizations', '0002_verification_branches_and_payouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('under_review', 'Under review'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('closed', 'Closed')], default='draft', max_length=24)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reserve_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('failure_reason', models.CharField(blank=True, max_length=240, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_settlements', to='identity.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_settlements', to='identity.user')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='settlements', to='organizations.office')),
            ],
            options={
                'db_table': 'settlements',
            },
        ),
        migrations.CreateModel(
            name='SettlementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('electronic_payable', 'Electronic payable'), ('direct_commission', 'Direct commission'), ('netting', 'Netting'), ('refund', 'Refund'), ('reserve', 'Reserve'), ('frozen_dispute', 'Frozen dispute'), ('adjustment', 'Adjustment')], max_length=40)),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='settlement_items', to='bookings.booking')),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='settlement_items', to='finance.commission')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='finance.settlement')),
            ],
            options={
                'db_table': 'settlement_items',
            },
        ),
        migrations.CreateModel(
            name='CommissionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('calculation_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('hybrid', 'Hybrid')], max_length=20)),
                ('percentage_rate', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_commission_profiles', to='identity.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_commission_profiles', to='identity.user')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='finance.commissionprofile')),
            ],
            options={
                'db_table': 'commission_profiles',
                'indexes': [models.Index(fields=['code', 'status', '-version'], name='ix_commission_profile_current')],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='uq_commission_profile_version'), models.CheckConstraint(condition=models.Q(('percentage_rate__gte', 0), ('fixed_amount__gte', 0)), name='ck_commission_profile_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='FinancialDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('decided', 'Decided'), ('closed', 'Closed')], default='open', max_length=24)),
                ('category', models.CharField(max_length=60)),
                ('disputed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('opened_by_type', models.CharField(choices=[('customer', 'Customer'), ('office', 'Office'), ('platform', 'Platform'), ('provider', 'Provider')], max_length=20)),
                ('opened_by_id', models.UUIDField(blank=True, null=True)),
                ('decision_code', models.CharField(blank=True, max_length=80, null=True)),
                ('decision_summary', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_financial_disputes', to='identity.user')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='financial_disputes', to='bookings.booking')),
            ],
            options={
                'db_table': 'disputes',
                'indexes': [models.Index(fields=['booking', 'status'], name='ix_dispute_booking_status'), models.Index(fields=['status', 'opened_at'], name='ix_dispute_queue')],
                'constraints': [models.CheckConstraint(condition=models.Q(('disputed_amount__isnull', True), ('disputed_amount__gte', 0), _connector='OR'), name='ck_dispute_amount_nonnegative')],
            },
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['office', 'currency', 'status'], name='ix_settlement_office_status'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['status', 'period_end'], name='ix_settlement_platform_queue'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.UniqueConstraint(fields=('office', 'period_start', 'period_end', 'currency'), name='uq_settlement_office_period_currency'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='ck_settlement_period'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('created_by')), _negated=True), _connector='OR'), name='ck_settlement_dual_approval'),
        ),
        migrations.AddIndex(
            model_name='settlementitem',
            index=models.Index(fields=['settlement', 'item_type'], name='ix_settlement_item_type'),
        ),
        migrations.AddIndex(
            model_name='settlementitem',
            index=models.Index(fields=['booking', 'currency'], name='ix_settlement_item_booking'),
        ),
        migrations.AddConstraint(
            model_name='settlementitem',
            constraint=models.UniqueConstraint(fields=('settlement', 'item_type', 'source_type', 'source_id'), name='uq_settlement_item_source'),
        ),
        migrations.AddConstraint(
            model_name='settlementitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_settlement_item_nonnegative'),
        ),
    ]
