# Generated by Django 5.2.16 on 2026-07-21 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_settlement_settlementitem_commissionprofile_and_more'),
        ('identity', '0003_platformroleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialdispute',
            name='appeal_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialdispute',
            name='appealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialdispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_office', 'Awaiting office'), ('under_review', 'Under review'), ('decided', 'Decided'), ('appealed', 'Appealed'), ('closed', 'Closed')], default='open', max_length=24),
        ),
        migrations.CreateModel(
            name='FinancialDisputeAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filed_by_type', models.CharField(choices=[('customer', 'Customer'), ('office', 'Office'), ('platform', 'Platform')], max_length=20)),
                ('reason', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('filed_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='appeal', to='finance.financialdispute')),
                ('filed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='financial_dispute_appeals', to='identity.user')),
            ],
            options={
                'db_table': 'dispute_appeals',
            },
        ),
        migrations.CreateModel(
            name='FinancialDisputeDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('initial', 'Initial'), ('appeal', 'Appeal')], max_length=16)),
                ('decision_code', models.CharField(max_length=80)),
                ('reasoning', models.TextField()),
                ('financial_effect_type', models.CharField(choices=[('none', 'None'), ('office_credit', 'Office credit'), ('office_debit', 'Office debit'), ('customer_compensation', 'Customer compensation')], default='none', max_length=32)),
                ('financial_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('appeal_allowed_until', models.DateTimeField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='financial_dispute_decisions', to='identity.user')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='decisions', to='finance.financialdispute')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dispute_decisions', to='finance.ledgerentry')),
            ],
            options={
                'db_table': 'dispute_decisions',
                'indexes': [models.Index(fields=['dispute', 'stage'], name='ix_dispute_decision_stage')],
                'constraints': [models.UniqueConstraint(fields=('dispute', 'stage'), name='uq_dispute_decision_stage'), models.CheckConstraint(condition=models.Q(('financial_amount__gte', 0)), name='ck_dispute_effect_nonnegative')],
            },
        ),
    ]
