# Generated by Django 5.2.16 on 2026-07-20 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_session_mfa_evidence'),
        ('organizations', '0002_verification_branches_and_payouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('policy_type', models.CharField(choices=[('cancellation', 'Cancellation'), ('payment', 'Payment'), ('boarding', 'Boarding'), ('baggage', 'Baggage'), ('terms', 'Terms'), ('privacy', 'Privacy')], max_length=40)),
                ('owner_scope', models.CharField(choices=[('platform', 'Platform'), ('office', 'Office')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20)),
            ],
            options={
                'db_table': 'policy_templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('language', models.CharField(default='ar', max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('content_markdown', models.TextField()),
                ('rules_json', models.JSONField(default=dict)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_sha256', models.CharField(max_length=64)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='policy_versions', to='organizations.office')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='policies.policytemplate')),
            ],
            options={
                'db_table': 'policy_versions',
                'ordering': ['template__code', '-version_no'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('user', 'User'), ('office', 'Office'), ('booking', 'Booking')], max_length=20)),
                ('subject_id', models.UUIDField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.BinaryField(blank=True, null=True)),
                ('user_agent_hash', models.BinaryField(blank=True, null=True)),
                ('accepted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='policy_acceptances', to='identity.user')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='acceptances', to='policies.policyversion')),
            ],
            options={
                'db_table': 'policy_acceptances',
            },
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['template', 'office', 'effective_from'], name='ix_policy_effective'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_policy_version_window'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('office__isnull', False)), fields=('template', 'office', 'version_no', 'language'), name='uq_office_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('office__isnull', True)), fields=('template', 'version_no', 'language'), name='uq_platform_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='policyacceptance',
            constraint=models.UniqueConstraint(fields=('policy_version', 'subject_type', 'subject_id'), name='uq_policy_acceptance_subject'),
        ),
    ]
