# Generated by Django 5.2.16 on 2026-07-21 12:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_session_mfa_evidence'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('platform', 'Platform'), ('office', 'Office'), ('branch', 'Branch'), ('route', 'Route'), ('trip', 'Trip')], max_length=20)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('key', models.CharField(max_length=120)),
                ('value_json', models.JSONField()),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('string', 'String'), ('duration', 'Duration'), ('object', 'Object'), ('list', 'List')], max_length=20)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=240)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_configuration_values', to='identity.user')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_configuration_values', to='identity.user')),
            ],
            options={
                'db_table': 'configuration_values',
                'ordering': ['key', '-effective_from'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id', 'key', 'effective_from'], name='ix_config_effective')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_configuration_window'), models.CheckConstraint(condition=models.Q(models.Q(('scope_id__isnull', True), ('scope_type', 'platform')), models.Q(models.Q(('scope_type', 'platform'), _negated=True), ('scope_id__isnull', False)), _connector='OR'), name='ck_platform_configuration_scope'), models.UniqueConstraint(condition=models.Q(('scope_type', 'platform')), fields=('scope_type', 'key', 'effective_from'), name='uq_platform_config_time'), models.UniqueConstraint(condition=models.Q(('scope_type', 'platform'), _negated=True), fields=('scope_type', 'scope_id', 'key', 'effective_from'), name='uq_scoped_config_time')],
            },
        ),
    ]
