# Generated by Django 5.2.16 on 2026-07-21 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_session_mfa_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('user', 'User'), ('office', 'Office'), ('employee', 'Employee'), ('device', 'Device')], max_length=30)),
                ('subject_id', models.UUIDField()),
                ('score', models.DecimalField(decimal_places=3, max_digits=6)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('step_up', 'Step up'), ('manual_review', 'Manual review'), ('restrict', 'Restrict'), ('block', 'Block')], max_length=24)),
                ('model_version', models.CharField(max_length=40)),
                ('signals', models.JSONField(default=dict)),
                ('review_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_assessments',
                'indexes': [models.Index(fields=['subject_type', 'subject_id', '-created_at'], name='ix_risk_subject_time'), models.Index(fields=['decision', 'review_status', '-created_at'], name='ix_risk_decision_review')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='ck_risk_score_range')],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('request_type', models.CharField(choices=[('access', 'Access'), ('export', 'Export'), ('correct', 'Correct'), ('delete', 'Delete'), ('restrict', 'Restrict'), ('object', 'Object')], max_length=24)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('identity_verification', 'Identity verification'), ('in_progress', 'In progress'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=24)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='data_subject_requests', to='identity.user')),
            ],
            options={
                'db_table': 'data_subject_requests',
                'indexes': [models.Index(fields=['status', 'due_at'], name='ix_dsr_status_due')],
            },
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('booking', 'Booking'), ('user', 'User'), ('payment', 'Payment'), ('dispute', 'Dispute'), ('office', 'Office')], max_length=40)),
                ('subject_id', models.UUIDField()),
                ('reason', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='placed_legal_holds', to='identity.user')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='released_legal_holds', to='identity.user')),
            ],
            options={
                'db_table': 'legal_holds',
                'indexes': [models.Index(fields=['subject_type', 'subject_id', 'active'], name='ix_legal_hold_subject')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('subject_type', 'subject_id'), name='uq_active_legal_hold')],
            },
        ),
        migrations.CreateModel(
            name='RiskChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.BinaryField()),
                ('token_hash', models.BinaryField(blank=True, null=True, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='challenge', to='securityops.riskassessment')),
            ],
            options={
                'db_table': 'risk_challenges',
                'indexes': [models.Index(fields=['expires_at', 'consumed_at'], name='ix_risk_challenge_expiry')],
            },
        ),
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_scope', models.CharField(choices=[('user', 'User'), ('office', 'Office'), ('platform', 'Platform'), ('booking', 'Booking'), ('support', 'Support')], max_length=30)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=60)),
                ('object_key', models.TextField(unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('scan_status', models.CharField(choices=[('initiated', 'Initiated'), ('quarantined', 'Quarantined'), ('clean', 'Clean'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='initiated', max_length=20)),
                ('retention_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='stored_files', to='identity.user')),
            ],
            options={
                'db_table': 'stored_files',
                'indexes': [models.Index(fields=['owner_scope', 'owner_id', 'scan_status'], name='ix_file_owner_status'), models.Index(fields=['scan_status', 'retention_until'], name='ix_file_retention')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='ck_stored_file_positive_size'), models.UniqueConstraint(fields=('owner_scope', 'owner_id', 'purpose', 'sha256'), name='uq_stored_file_owner_purpose_hash')],
            },
        ),
    ]
