# Generated by Django 5.2.16 on 2026-07-20 23:32

import common.ids
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_verification_branches_and_payouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seat_layouts', to='organizations.office')),
                ('name', models.CharField(max_length=160)),
                ('layout_type', models.CharField(choices=[('2+2', '2+2'), ('2+1', '2+1'), ('custom', 'Custom')], max_length=20)),
                ('seat_count', models.PositiveSmallIntegerField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'seat_layouts',
                'ordering': ['name', '-version'],
                'indexes': [models.Index(fields=['office', 'status'], name='ix_layout_office_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('seat_count__gt', 0)), name='ck_seat_layout_count'), models.UniqueConstraint(fields=('office', 'name', 'version'), name='uq_seat_layout_version')],
            },
        ),
        migrations.CreateModel(
            name='SeatLayoutSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='fleet.seatlayout')),
                ('seat_code', models.CharField(max_length=12)),
                ('row_no', models.PositiveSmallIntegerField()),
                ('column_no', models.PositiveSmallIntegerField()),
                ('seat_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('single', 'Single'), ('accessible', 'Accessible'), ('crew', 'Crew'), ('blocked', 'Blocked')], default='standard', max_length=20)),
                ('is_sellable', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'seat_layout_seats',
                'ordering': ['row_no', 'column_no', 'seat_code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('column_no__gt', 0), ('row_no__gt', 0)), name='ck_layout_seat_position'), models.UniqueConstraint(fields=('layout', 'seat_code'), name='uq_layout_seat_code'), models.UniqueConstraint(fields=('layout', 'row_no', 'column_no'), name='uq_layout_seat_position')],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='SeatAdjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacencies', to='fleet.seatlayout')),
                ('seat_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacent_as_a', to='fleet.seatlayoutseat')),
                ('seat_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacent_as_b', to='fleet.seatlayoutseat')),
                ('adjacency_type', models.CharField(choices=[('same_unit', 'Same unit'), ('aisle', 'Across aisle'), ('nearby', 'Nearby')], default='same_unit', max_length=20)),
            ],
            options={
                'db_table': 'seat_adjacencies',
                'constraints': [models.CheckConstraint(condition=models.Q(('seat_a_id__lt', models.F('seat_b_id'))), name='ck_seat_adjacency_order'), models.UniqueConstraint(fields=('layout', 'seat_a', 'seat_b'), name='pk_seat_adjacencies')],
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicles', to='organizations.office')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vehicles', to='organizations.transportoperator')),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('plate_number', models.CharField(max_length=40)),
                ('fleet_number', models.CharField(blank=True, max_length=40, null=True)),
                ('seat_layout', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vehicles', to='fleet.seatlayout')),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of service'), ('retired', 'Retired')], default='active', max_length=20)),
                ('make_model', models.CharField(blank=True, max_length=160, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['plate_number'],
                'indexes': [models.Index(fields=['office', 'status'], name='ix_vehicle_office_status')],
                'constraints': [models.UniqueConstraint(fields=('office', 'plate_number'), name='uq_vehicle_plate_office'), models.CheckConstraint(condition=models.Q(('year__isnull', True), models.Q(('year__gte', 1980), ('year__lte', 2100)), _connector='OR'), name='ck_vehicle_year')],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documents', to='fleet.vehicle')),
                ('document_type', models.CharField(max_length=64)),
                ('storage_object_key', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vehicle_documents',
                'indexes': [models.Index(fields=['vehicle', 'status', 'expires_at'], name='ix_vehicle_doc_validity')],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'document_type', 'sha256'), name='uq_vehicle_document_hash')],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='drivers', to='organizations.transportoperator')),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number_ciphertext', models.BinaryField()),
                ('license_last4', models.CharField(blank=True, max_length=8, null=True)),
                ('license_expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['operator', 'status'], name='ix_driver_operator_status')],
                'constraints': [],
            },
        ),
    ]
