"use client";

import { FormEvent, useState } from "react";
import { browserApiUrl } from "@/lib/public-api";
import { useStoredAccessToken } from "@/lib/auth";

type Office = { id: string; trade_name: string; legal_name: string; status: string; default_currency: string };
type OfficeDetail = Office & { branches_count: number; members_count: number; open_violations: number; status_history: Array<{ id: string; previous_status: string; new_status: string; reason: string; created_at: string }> };
type Violation = { id: string; code: string; severity: string; status: string; description: string; created_at: string };
type AuditRow = { id: string; occurred_at: string; actor: string | null; action: string; object_type: string; object_id: string; reason_code: string | null };
type Report = Record<string, unknown>;

function headers(token: string, mutation = false): HeadersInit { return { Authorization: `Bearer ${token.trim()}`, ...(mutation ? { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() } : {}) }; }
function errorMessage(payload: unknown): string { if (typeof payload === "object" && payload !== null && "error" in payload && typeof payload.error === "object" && payload.error !== null && "message" in payload.error && typeof payload.error.message === "string") return payload.error.message; return "تعذر تنفيذ العملية."; }

export function PlatformOfficeAdminConsole() {
  const [token, setToken] = useStoredAccessToken(); const [query, setQuery] = useState(""); const [offices, setOffices] = useState<Office[]>([]); const [selected, setSelected] = useState<OfficeDetail | null>(null); const [violations, setViolations] = useState<Violation[]>([]); const [status, setStatus] = useState("active"); const [reason, setReason] = useState(""); const [code, setCode] = useState(""); const [severity, setSeverity] = useState("P2"); const [description, setDescription] = useState(""); const [message, setMessage] = useState<string | null>(null);
  async function search() { const response = await fetch(browserApiUrl(`/v1/platform/offices?q=${encodeURIComponent(query)}`), { headers: headers(token) }); const payload = await response.json() as Office[] | unknown; if (!response.ok || !Array.isArray(payload)) { setMessage(errorMessage(payload)); return; } setOffices(payload); }
  async function openOffice(id: string) { const [detailResponse, violationResponse] = await Promise.all([fetch(browserApiUrl(`/v1/platform/offices/${id}`), { headers: headers(token) }), fetch(browserApiUrl(`/v1/platform/offices/${id}/violations`), { headers: headers(token) })]); const detail = await detailResponse.json() as OfficeDetail | unknown; const violationPayload = await violationResponse.json() as Violation[] | unknown; if (!detailResponse.ok || typeof detail !== "object" || detail === null || !violationResponse.ok || !Array.isArray(violationPayload)) { setMessage(errorMessage(detail)); return; } setSelected(detail as OfficeDetail); setViolations(violationPayload); setStatus((detail as OfficeDetail).status); }
  async function changeStatus(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const response = await fetch(browserApiUrl(`/v1/platform/offices/${selected.id}/status`), { method: "POST", headers: headers(token, true), body: JSON.stringify({ status, reason }) }); const payload = await response.json() as { requires_approval?: boolean; approval?: { id?: string } } | unknown; if (!response.ok) { setMessage(errorMessage(payload)); return; } if (typeof payload === "object" && payload !== null && "requires_approval" in payload && payload.requires_approval) { const approvalId = "approval" in payload && typeof payload.approval === "object" && payload.approval !== null && "id" in payload.approval ? String(payload.approval.id) : ""; setMessage(`تم إنشاء طلب اعتماد مزدوج${approvalId ? `: ${approvalId}` : ""}. لم تتغير حالة المكتب بعد.`); } else { setMessage("تم تغيير حالة المكتب وتسجيل القرار مع الحفاظ على الحجوزات القائمة."); } await openOffice(selected.id); }
  async function addViolation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const response = await fetch(browserApiUrl(`/v1/platform/offices/${selected.id}/violations`), { method: "POST", headers: headers(token, true), body: JSON.stringify({ code, severity, description, evidence: {} }) }); const payload = await response.json() as Violation | unknown; if (!response.ok || typeof payload !== "object" || payload === null) { setMessage(errorMessage(payload)); return; } setCode(""); setDescription(""); setMessage("تم إنشاء المخالفة وحالة الدعم المرتبطة."); await openOffice(selected.id); }
  async function closeViolation(id: string) { if (!selected) return; const response = await fetch(browserApiUrl(`/v1/platform/offices/${selected.id}/violations/${id}/commands`), { method: "POST", headers: headers(token, true), body: JSON.stringify({ command: "close", reason: "تمت المعالجة والتحقق من الإغلاق" }) }); const payload = await response.json() as unknown; if (!response.ok) { setMessage(errorMessage(payload)); return; } await openOffice(selected.id); }
  return <section className="workspace-grid"><article className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">Office governance</p><h2>البحث والإشراف</h2></div><button onClick={search}>بحث</button></div><div className="stack-form"><label>جلسة المنصة<input type="password" value={token} onChange={(event) => setToken(event.target.value)} /></label><label>اسم المكتب<input value={query} onChange={(event) => setQuery(event.target.value)} /></label></div><div className="data-table">{offices.map((office) => <button className="data-row" key={office.id} onClick={() => openOffice(office.id)}><div><strong>{office.trade_name}</strong><small>{office.legal_name}</small></div><span className="state-badge state-active">{office.status}</span><small>{office.default_currency}</small></button>)}</div></article><article className="workspace-panel">{selected ? <><div className="section-heading"><div><p className="eyebrow">{selected.id}</p><h2>{selected.trade_name}</h2></div><span className="state-badge state-pending">{selected.open_violations} مخالفات</span></div><div className="success-grid"><div><span>الفروع</span><strong>{selected.branches_count}</strong></div><div><span>المستخدمون</span><strong>{selected.members_count}</strong></div></div><form className="stack-form" onSubmit={changeStatus}><label>الحالة<select value={status} onChange={(event) => setStatus(event.target.value)}>{["active","restricted","no_new_bookings","suspended","terminated"].map((value) => <option key={value}>{value}</option>)}</select></label><label>السبب<textarea minLength={10} value={reason} onChange={(event) => setReason(event.target.value)} /></label><button>تحديث الحالة</button></form><form className="stack-form violation-form" onSubmit={addViolation}><label>رمز المخالفة<input value={code} onChange={(event) => setCode(event.target.value)} /></label><label>الخطورة<select value={severity} onChange={(event) => setSeverity(event.target.value)}>{["P0","P1","P2","P3","P4"].map((value) => <option key={value}>{value}</option>)}</select></label><label>الوصف<textarea minLength={10} value={description} onChange={(event) => setDescription(event.target.value)} /></label><button>إنشاء مخالفة</button></form><div className="data-table">{violations.map((item) => <div className="data-row" key={item.id}><div><strong>{item.code}</strong><small>{item.description}</small></div><span className="state-badge state-cancelled">{item.severity} · {item.status}</span>{item.status !== "closed" ? <button className="secondary-button" onClick={() => closeViolation(item.id)}>إغلاق</button> : <small>مغلقة</small>}</div>)}</div></> : <div className="empty-state"><p>اختر مكتبًا لعرض قراراته ومخالفاته.</p></div>}{message ? <p className="form-note">{message}</p> : null}</article></section>;
}

export function AuditConsole() {
  const [token, setToken] = useStoredAccessToken(); const [officeId, setOfficeId] = useState(""); const [action, setAction] = useState(""); const [rows, setRows] = useState<AuditRow[]>([]); const [message, setMessage] = useState<string | null>(null);
  async function load() { const query = new URLSearchParams(); if (officeId) query.set("office_id", officeId); if (action) query.set("action", action); const response = await fetch(browserApiUrl(`/v1/platform/audit-logs?${query}`), { headers: headers(token) }); const payload = await response.json() as { results?: AuditRow[] } | unknown; if (!response.ok || typeof payload !== "object" || payload === null || !("results" in payload) || !Array.isArray(payload.results)) { setMessage(errorMessage(payload)); return; } setRows(payload.results); }
  return <section className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">Append-only audit</p><h2>سجل التدقيق</h2></div><button onClick={load}>تحديث</button></div><div className="stack-form notification-filters"><label>جلسة المنصة<input type="password" value={token} onChange={(event) => setToken(event.target.value)} /></label><label>معرف المكتب<input value={officeId} onChange={(event) => setOfficeId(event.target.value)} /></label><label>الإجراء<input value={action} onChange={(event) => setAction(event.target.value)} /></label></div><div className="data-table">{rows.map((row) => <div className="data-row" key={row.id}><div><strong>{row.action}</strong><small>{row.actor ?? "system"} · {row.object_type}:{row.object_id}</small></div><span className="state-badge state-active">{row.reason_code ?? "—"}</span><small>{new Date(row.occurred_at).toLocaleString("ar")}</small></div>)}</div>{message ? <p className="form-note">{message}</p> : null}</section>;
}

export function ReportConsole({ scope }: { scope: "office" | "platform" }) {
  const [token, setToken] = useStoredAccessToken(); const [report, setReport] = useState<Report | null>(null); const [message, setMessage] = useState<string | null>(null);
  async function load() { const response = await fetch(browserApiUrl(`/v1/${scope}/reports/summary`), { headers: headers(token) }); const payload = await response.json() as Report | unknown; if (!response.ok || typeof payload !== "object" || payload === null) { setMessage(errorMessage(payload)); return; } setReport(payload as Report); }
  return <section className="workspace-panel"><div className="section-heading"><div><p className="eyebrow">Live summary</p><h2>{scope === "office" ? "تقرير المكتب" : "تقرير المنصة"}</h2></div><button onClick={load}>تحديث</button></div><label className="stack-form">جلسة {scope === "office" ? "المكتب" : "المنصة"}<input type="password" value={token} onChange={(event) => setToken(event.target.value)} /></label>{report ? <pre className="report-json">{JSON.stringify(report, null, 2)}</pre> : <div className="empty-state"><p>حمّل التقرير لعرض المؤشرات الحالية.</p></div>}{message ? <p className="form-note">{message}</p> : null}</section>;
}
