# Generated by Django 5.2.16 on 2026-07-20 22:57

import common.ids
import django.db.models.deletion
import identity.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(default=common.ids.generate_public_id, editable=False, max_length=26, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_e164', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, db_column='password_hash', max_length=128, null=True)),
                ('full_name', models.CharField(max_length=160)),
                ('preferred_language', models.CharField(default='ar', max_length=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled'), ('deleted', 'Deleted')], default='active', max_length=24)),
                ('is_platform_staff', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', identity.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MfaMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('totp', 'TOTP'), ('webauthn', 'WebAuthn'), ('recovery', 'Recovery')], max_length=20)),
                ('secret_ciphertext', models.BinaryField(blank=True, null=True)),
                ('credential_id', models.BinaryField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mfa_methods',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name_ar', models.CharField(max_length=160)),
                ('risk_level', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensitive'), ('critical', 'Critical')], default='normal', max_length=12)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('scope_type', models.CharField(choices=[('platform', 'Platform'), ('office', 'Office'), ('branch', 'Branch')], max_length=20)),
                ('name_ar', models.CharField(max_length=120)),
                ('is_system', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint_hash', models.BinaryField()),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
                ('trusted_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_devices',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.BinaryField(unique=True)),
                ('ip_hash', models.BinaryField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='customer_profile', serialize=False, to='identity.user')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=12, null=True)),
                ('nationality_code', models.CharField(blank=True, max_length=2, null=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_profiles',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone_e164__isnull', False), _connector='OR'), name='ck_user_has_identifier'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='uq_users_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_e164__isnull', False)), fields=('phone_e164',), name='uq_users_phone'),
        ),
        migrations.AddField(
            model_name='mfamethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='mfa_methods', to='identity.user'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='identity.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='identity.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='identity.RolePermission', to='identity.permission'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='devices', to='identity.user'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='identity.userdevice'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions', to='identity.user'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='pk_role_permissions'),
        ),
        migrations.AddConstraint(
            model_name='userdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_fingerprint_hash'), name='uq_user_device_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'revoked_at', 'expires_at'], name='ix_user_sessions_active'),
        ),
    ]
