# Generated by Django 5.2.16 on 2026-07-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='mfa_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
