# Generated by Django 5.2.16 on 2026-07-21 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_session_mfa_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_platform_roles', to='identity.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='platform_assignments', to='identity.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='platform_role_assignments', to='identity.user')),
            ],
            options={
                'db_table': 'platform_role_assignments',
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='ix_platform_role_active')],
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='uq_platform_user_role')],
            },
        ),
    ]
