# Generated by Django 5.2.16 on 2026-07-21 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('used', 'Used'), ('expired', 'Expired')], default='active', max_length=20)),
                ('qr_token_hash', models.BinaryField(unique=True)),
                ('qr_payload_signature', models.BinaryField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='bookings.booking')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='bookings.bookingpassenger')),
                ('seat_assignment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='bookings.seatassignment')),
            ],
            options={
                'db_table': 'tickets',
                'indexes': [models.Index(fields=['booking', 'status'], name='ix_ticket_booking_status')],
                'constraints': [models.UniqueConstraint(fields=('passenger', 'version_no'), name='uq_ticket_passenger_version'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('passenger',), name='uq_active_ticket')],
            },
        ),
    ]
